// flow-typed signature: 458bf016223db77665e4444cfd3a2fd7
// flow-typed version: <<STUB>>/rpi-gpio_v^2.1.0/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rpi-gpio'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rpi-gpio' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rpi-gpio/examples/listen-pin' {
  declare module.exports: any;
}

declare module 'rpi-gpio/examples/read-pin' {
  declare module.exports: any;
}

declare module 'rpi-gpio/examples/unexport' {
  declare module.exports: any;
}

declare module 'rpi-gpio/examples/voltage-cycling' {
  declare module.exports: any;
}

declare module 'rpi-gpio/examples/write-pin-on' {
  declare module.exports: any;
}

declare module 'rpi-gpio/examples/write-pin' {
  declare module.exports: any;
}

declare module 'rpi-gpio/rpi-gpio' {
  declare module.exports: any;
}

declare module 'rpi-gpio/test/integration/main' {
  declare module.exports: any;
}

declare module 'rpi-gpio/test/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rpi-gpio/examples/listen-pin.js' {
  declare module.exports: $Exports<'rpi-gpio/examples/listen-pin'>;
}
declare module 'rpi-gpio/examples/read-pin.js' {
  declare module.exports: $Exports<'rpi-gpio/examples/read-pin'>;
}
declare module 'rpi-gpio/examples/unexport.js' {
  declare module.exports: $Exports<'rpi-gpio/examples/unexport'>;
}
declare module 'rpi-gpio/examples/voltage-cycling.js' {
  declare module.exports: $Exports<'rpi-gpio/examples/voltage-cycling'>;
}
declare module 'rpi-gpio/examples/write-pin-on.js' {
  declare module.exports: $Exports<'rpi-gpio/examples/write-pin-on'>;
}
declare module 'rpi-gpio/examples/write-pin.js' {
  declare module.exports: $Exports<'rpi-gpio/examples/write-pin'>;
}
declare module 'rpi-gpio/rpi-gpio.js' {
  declare module.exports: $Exports<'rpi-gpio/rpi-gpio'>;
}
declare module 'rpi-gpio/test/integration/main.js' {
  declare module.exports: $Exports<'rpi-gpio/test/integration/main'>;
}
declare module 'rpi-gpio/test/main.js' {
  declare module.exports: $Exports<'rpi-gpio/test/main'>;
}
